### PR TITLE
Attempt to fix CI

### LINKED ISSUE #186: [BUG] Cargo test GH action unable to run
Currently the tests are not being run when a PR is opened due to a problem with the simulated Omicron. 

```console
omicron-dev: populating database
omicron-dev: populating Omicron database: db error: ERROR: invalid privilege type INSERT for database: ERROR: invalid privilege type INSERT for database
make: *** [Makefile:115: start-omicron] Error 1
Error: Process completed with exit code 2.
```

### PR DESCRIPTION
**Pull request by karencfv**
Attempts to fix https://github.com/oxidecomputer/cli/issues/186

### CODE REVIEW

**Comment by karencfv** [comment]
Heya @smklein and @davepacheco sorry for the ping, but I see you both have worked on https://github.com/oxidecomputer/omicron/blob/main/test-utils/src/dev/db.rs 😄  

We're having some trouble in dev tools land with running the simulated Omicron on our CI. I tried several things to fix the `populating Omicron database: db error: ERROR: invalid privilege type INSERT for database: ERROR: invalid privilege type INSERT for database` error, and then flailed and floundered for a while, but alas got nowhere :'(

Would either of you have an idea on how I could go on about fixing this? Help would be much appreciated!

**Comment by smklein** [comment]
Are you seeing this locally? I checked out the CLI at `main`, and `make start-omicron` appeared to work fine on my machine.

(I see that CI on main is also failing, but this is an interesting data point)

**Comment by smklein** [comment]
As a breakdown, the failure appears to be coming from here:

https://github.com/oxidecomputer/cli/blob/d7c0598a8806a9392808b4627e16b78ac1117ea7/Makefile#L114-L121

This invokes the "DB populate" command from `omicron-dev`: https://github.com/oxidecomputer/omicron/blob/0d2410071711d7ecdd3c115ebfb93b3ea3e1e16b/test-utils/src/bin/omicron-dev.rs#L24

Which should just be doing a batch-execution of our "dbinit.sql" file: https://github.com/oxidecomputer/omicron/blob/0d2410071711d7ecdd3c115ebfb93b3ea3e1e16b/test-utils/src/dev/db.rs#L640-L654

That [dbinit.sql file](https://github.com/oxidecomputer/omicron/blob/main/common/src/sql/dbinit.sql) is tested pretty regularly within Omicron - as the name implies, it's just a bunch of SQL to initialize the DB. but that looks like the source of the error on CI, somehow.

**Comment by smklein** [comment]
Based on this info, I wonder if the Makefile - which depends on an untagged `cockroachdb/cockroach` Docker container - is possibly problematic. Omicron also depends on CRDB, but that version moves around with Omicron (currently it's at [v22.2.9](https://github.com/oxidecomputer/omicron/blob/main/tools/cockroachdb_version)).

I've been experimenting with this here: https://github.com/oxidecomputer/cli/pull/203 - I think the CI is still broken, but it appears to be getting further along.

**Comment by karencfv** [comment]
aaaaahhhhhh thanks so much!!! 🙇‍♀️ this is great, I'll continue the conversation there

**Comment by karencfv** [comment]
Closing as issue fixed in https://github.com/oxidecomputer/cli/pull/203 🎉

**Pull request closed without merging**
