### PR TITLE
Login with OAuth 2.0 Device Authorization Grant

### PR DESCRIPTION
**Pull request by plotnick**
Depends on [Omicron#1194](https://github.com/oxidecomputer/omicron/pull/1194).

### CODE REVIEW

**Review by karencfv — APPROVED** [review]
Thanks for working on this @plotnick ! In the interest of moving this along for the demo, I'm approving for you to merge :)

If you have a few spare minutes could you add a bit of documentation to the README about this feature? Can be in a follow up PR if that work better for you

**Comment by plotnick** [comment]
> If you have a few spare minutes could you add a bit of documentation to the README about this feature?

Done in 3b20d3c. We should also update the CLI user manual, but that I will take as a follow-up.

**Comment by karencfv** [comment]
thanks for updating the readme!!!

**Comment by karencfv** [comment]
@plotnick I've updated the docs so they'll be generated on the docs website on release https://github.com/oxidecomputer/cli/pull/215. Thanks again for adding this command!

**Pull request merged**
