### PR TITLE
Change description for format parameter

### LINKED ISSUE #229: Output format
~More often than not, as an SRE, it’s necessary to toggle between human readable and json output often. Generally this can be set through a global flag, which makes it very easy to switch from one output format to another. With our CLI this has to be set through another command  `$ oxide config set format json`. Generally we want to give our users less commands to have to remember, and less steps to get their work done.~

~There should be a global `--json` flag~

Currently there is a `--format` flag in most commands which accepts different values. From the description it's not very clear as to what those values should be `-f, --format <FORMAT> Output format`.

This flag should be global and the description should say what values are accepted and what they do.

### PR DESCRIPTION
**Pull request by ryaeng**
Fixes #229.

### CODE REVIEW

**Comment by plotnick** [comment]
The failure here is that the tests are comparing the docstrings to a previously known value. It's a bit buried in the output, but the hint is here:
```
thread 'test_do_gen' panicked at 'assertion failed: string doesn't match the contents of file: "tests/gen/disks.rs.gen" see diffset above
398
                set EXPECTORATE=overwrite if these changes are intentional', cli-macro-impl/tests/tests.rs:22:5
```
If you run `EXPECTORATE=overwrite cargo test` locally (on your machine) and then commit the updated files, it should work (I think).

**Comment by ryaeng** [comment]
Thanks, Alex. I'll give it a shot.

The errors that I'm seeing locally are in regards to OXIDE_TEST_HOST. Do I
need variables set in order to test locally?

**Comment by plotnick** [comment]
> The errors that I'm seeing locally are in regards to OXIDE_TEST_HOST. Do I need variables set in order to test locally?

In general, yes, you need `OXIDE_TEST_HOST` set to the URL of a running Nexus instance to run all the tests. But the test that's failing here actually doesn't need that, since it's not running any API functions; try `EXPECTORATE=overwrite cargo test -p cli-macro-impl test_do_gen` to run just that one test.

**Comment by ryaeng** [comment]
Done.

**Comment by karencfv** [comment]
Heya @plotnick, looks like the auth test failed. There's a PR in omicron that needs to be merged to get those to pass right?

**Review by plotnick — APPROVED** [review]
The latest test failures have nothing to do with your changes @ryaeng, they're because the `OXIDE_TEST_TOKEN` variable is missing in the test execution environment, since the workflow pulls that out of GitHub secrets that only exist in the source repository. (The test token isn't really secret, so in theory we could change that.)

So I think this is good to go.

**Review by karencfv — APPROVED** [review]
Thanks for the clarification @plotnick, I'll add that variable

**Comment by karencfv** [comment]
While I wait for permissions on this repo to add GH secrets we can safely merge this PR. Thanks @ryaeng for the fix!

**Pull request merged**
