### PR TITLE
Adds support for writing memory and disk sizes as bytes, MiB, GB, etc

### PR DESCRIPTION
**Pull request by bnaecker**

### CODE REVIEW

**Comment by bnaecker** [comment]
I added a statement printing the parsed `u64` to the macro, to be sure this was all working as expected. Here's what it shows:

```
bnaecker@shale : ~/cli $ cargo run -- instance create -o o -p p vm0
   Compiling cli-macro-impl v0.1.0 (/home/bnaecker/cli/cli-macro-impl)
   Compiling cli-macro v0.1.0 (/home/bnaecker/cli/cli-macro)
   Compiling oxide v0.2.2 (/home/bnaecker/cli)
    Finished dev [unoptimized + debuginfo] target(s) in 39.28s
     Running `target/debug/oxide instance create -o o -p p vm0`
instance description: vm0
instance hostname: vm0
instance memory: 1GiB
1073741824
instance ncpus: 4
^C
```

**Comment by jessfraz** [comment]
Awesome you can run 
```
EXPECTORATE=overwrite cargo test -p cli-macro-impl -- --nocapture
```
to regenerate that test code such that it should make the tests pass

**Comment by jessfraz** [comment]
should we make the output there like a sentence "using 1073741824 bytes" or something like that? idk

**Comment by bnaecker** [comment]
That output was a local modification I made to verify things were working, not in the actual commit. I can do that, though, if you think it's valuable.

**Comment by jessfraz** [comment]
ah no even better to not show it at all!

**Comment by bnaecker** [comment]
@rmustacc brought up the good point that someone will almost certainly confused binary and base-10 units, e.g., `MB` and `MiB`. Any ideas for handling that?

**Comment by jessfraz** [comment]
we could convert it for them like you were or show the conversion? Also lots of docs on it would likely help as well but no one reads docs haha

**Comment by bnaecker** [comment]
Yeah the proposal I had was to echo their input exactly, and then print it in base-2. For example

```
instance memory: 10GB
Using 10GB (9.31 GiB)`
```

**Comment by jessfraz** [comment]
yeah thats dope

**Comment by bnaecker** [comment]
Here's the updated behavior for a few cases:

```
bnaecker@shale : ~/cli $ cargo run -- instance create -o o -p p vm0
   Compiling oxide v0.2.2 (/home/bnaecker/cli)
    Finished dev [unoptimized + debuginfo] target(s) in 34.67s
     Running `target/debug/oxide instance create -o o -p p vm0`
instance description: vm0
instance hostname: vm0
instance memory: 10000
Using 10000 bytes (9.77 KiB)
instance ncpus:
bnaecker@shale : ~/cli $ cargo run -- instance create -o o -p p vm0
    Finished dev [unoptimized + debuginfo] target(s) in 0.14s
     Running `target/debug/oxide instance create -o o -p p vm0`
instance description: vm0
instance hostname: vm0
instance memory: 100mb
Using 100000000 bytes (95.37 MiB)
instance ncpus:
bnaecker@shale : ~/cli $ cargo run -- instance create -o o -p p vm0
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
     Running `target/debug/oxide instance create -o o -p p vm0`
instance description: vm0
instance hostname: vm0
instance memory: 1gib
Using 1073741824 bytes (1024.00 MiB)
instance ncpus:
```

**Comment by jessfraz** [comment]
Awesome, feel free to merge after cross passes, thanks!

**Pull request merged**
