### PR TITLE
add building instructions to README

### PR DESCRIPTION
**Pull request by jmpesp**

### CODE REVIEW

**Comment by jessfraz** [comment]
the make file is mostly for cross compiling, `cargo build` works just fine, can we make that part of the readme, the makefile is really more for cross compiling from one OS/ARCH to another

**Comment by jessfraz** [comment]
my kinda point of view is i just do dev with `cargo build` and use the CI to verify I didn't break the cross-compile, its a bit heavy to do the cross compile all the time

**Comment by jmpesp** [comment]
:+1:

**Comment by jessfraz** [comment]
thanks!

**Pull request merged**
