### PR TITLE
buildomat: add basic job to build an illumos "oxide" binary

### PR DESCRIPTION
**Pull request by jclulow**

### CODE REVIEW

**Comment by jessfraz** [comment]
this is what the bucket looks like for a release fwiw, idk if buildomat can use the same gcloud secret and upload there on release? then the main release action can poll and wait for the illumos binaries or something
Screen Shot 2022-03-23 at 3 25 41 PM

**Comment by jessfraz** [comment]
we could also do this? https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners 

nevermind illumos not supported

**Comment by jclulow** [comment]
So this will produce a binary at a predictable URL, which you could poll for in the Action presumably.  For the PR so far:

https://buildomat.eng.oxide.computer/public/file/oxidecomputer/cli/build-illumos/db60daf8282aea3e8a3344c3fda19da35aaca7ec/oxide.gz

The only thing you would need to fill in is the commit SHA, which presumably is easy to obtain from the action.  You could do something like (I have not tested this extensively):

```bash
#!/bin/bash

COMMIT=db60daf8282aea3e8a3344c3fda19da35aaca7ec

filebase='https://buildomat.eng.oxide.computer/public/file'
commitbase="$filebase/oxidecomputer/cli/build-illumos/$COMMIT"

start=$SECONDS
while :; do
        if (( SECONDS - start > 3600 )); then
                printf 'timed out waiting for artefact\n' >&2
                exit 1
        fi

        rm -f /tmp/oxide-x86_64-unknown-illumos.sha256
        if ! curl -fSsL -o /tmp/oxide-x86_64-unknown-illumos.sha256 \
            "$commitbase/oxide.sha256.txt"; then
                sleep 5
                continue
        fi

        rm -f /tmp/oxide-x86_64-unknown-illumos.gz
        if ! curl -fSsL -o /tmp/oxide-x86_64-unknown-illumos.gz \
            "$commitbase/oxide.gz"; then
                sleep 5
                continue
        fi

        rm -f /tmp/oxide-x86_64-unknown-illumos
        if ! gunzip /tmp/oxide-x86_64-unknown-illumos.gz; then
                rm -f /tmp/oxide-x86_64-unknown-illumos
                rm -f /tmp/oxide-x86_64-unknown-illumos.gz
                sleep 5
                continue
        fi

        exp=$(</tmp/oxide-x86_64-unknown-illumos.sha256)
        hav=$(sha256sum /tmp/oxide-x86_64-unknown-illumos | awk '{ print $1 }')

        if [[ "$exp" != "$hav" ]]; then
                rm -f /tmp/oxide-x86_64-unknown-illumos
                printf 'ERROR: hash %s != %s\n' "$exp" "$hav"
                sleep 5
                continue
        fi

        break
done
```

to poll for the file?

**Comment by jessfraz** [comment]
Sweet yeah this totally works then I can cp the   files to other storage

**Pull request merged**
